Dropdown в хедере
Lacsw/design-for-all pull request #1
Opened 2023-12-27 08:25 UTC by vitland

Добавил компонент DropdownNavigation. 
Принимает в себя прост "type". В зависимости от него список отрисовывается ссылками или кнопками с onClick  event.

2024-01-08 13:21 UTC, Lacsw requested changes
Отличная работа!

Отметил пару моментов и немного странно отрабатывает появление сайдбара)

https://github.com/Lacsw/design-for-all/assets/12248879/86c93abe-e31f-42c8-8f2c-b457b685e23a

2024-01-08 13:21 UTC, Lacsw commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +	title,
`title` не передается ни в один дроп, соотвественно у `img` нету `alt`

можно при передаче тайтла определять иконку дропа тем самым перенести иконки разных дропов внутрь компонента из хэдера и не передавать `titleIcon`

2024-01-08 13:21 UTC, Lacsw commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +import { NavLink } from 'react-router-dom';
давай все сторонние импорты определять выше внутренних

2024-01-08 13:21 UTC, Lacsw commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +								<li onMouseEnter={() => setIsSideMenuOpen(true)}>
тут и ниже в консоли ошибка отсутствия `key` при маппинге. Можно взять индекс или добавить `options.name` если мы уверенны в их уникальности.

[Keeping list items in order with key](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key)

2024-02-29 18:42 UTC, vitland commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +import { NavLink } from 'react-router-dom';
Поменял порядок

2024-02-29 18:42 UTC, vitland commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +								<li onMouseEnter={() => setIsSideMenuOpen(true)}>
Добавил.

2024-02-29 18:42 UTC, vitland commented on src/components/DropdownNavigation/DropdownNavigation.jsx
> +	title,
Решил все-такие передавать title в компонент, альты появились.

2024-02-29 18:42 UTC, vitland commented on src/components/DropdownNavigation/DropdownNavigation.css
> +.dropdown-navigation {
Добавил самой иконке, иначе весь dropdown показывается кликабельным.

2024-03-01 16:34 UTC, Lacsw approved these changes

2024-03-01 16:35 UTC, merged