Feat/partition tree
Lacsw/design-for-all pull request #16
Opened 2024-07-26 23:42 UTC by Cheremis88

2024-07-27 13:55 UTC, Kargobober requested changes

2024-07-27 14:34 UTC, Cheremis88 commented on src/components/TestTree/TreeItem.jsx
> +  const id = hasChildren ? data.id : data;
Функция создания дерева и передача оттуда пропсов устроены так, что если пункт списка не имеет подразделов, (т.е. является конечной статьёй), то в его `data` будет именно строковое значение. Поэтому я сначала проверяю, является ли `data` объектом, и если да, то беру `id` из поля этого объекта, если нет - то само значение `data`.

2024-07-27 14:35 UTC, Cheremis88 commented on src/components/TestTree/TreeItem.jsx
> +        ' tree-item__arrow_visible tree-item__arrow_on';
Отличное замечание!

2024-07-27 14:38 UTC, Cheremis88 commented on src/components/TestTree/TestTree.jsx
> +  }, [fetchPath, dispatch]);
Да, я вообще создал эту ветку, чтоб сделать функцию дерева, но увлёкся и дошёл до запросов и рендера)

2024-07-27 14:41 UTC, Cheremis88 commented on src/components/TestTree/TestTree.css
Компоненты списка этого меню рендерятся почти рекурсивно на основе созданного объекта дерева, т.е. там в `ul` находится `li`, который рождает свой `ul` со своими `li` и т.д. по кругу. Поэтому там много родителей и много детей. Так что надо подумать, как в таком случае изящно решить вопрос с ширинами.

2024-07-27 14:44 UTC, Cheremis88 commented on src/components/Catalog/CatalogArticle.jsx
> +                <img src={previewImage} alt="превью" className="article__image" />
Этот кусок я взял для наполнения из шаблонной верстки уже имеющегося компонента. Когда буду наводить порядок, всё исправлю и там, и у себя.

2024-07-27 14:45 UTC, Cheremis88 commented on src/components/Catalog/CatalogArticle.jsx
> +                timeUpdate={new Date(article.publication.last_update).toLocaleDateString()}
Согласен, все подобные куски я планировал перенести в нужные места)

2024-07-27 14:46 UTC, Cheremis88 commented on src/components/Catalog/CatalogArticle.css
> +  box-sizing: border-box;
Что ещё делает CSSBaseline? Для чего он здесь?

2024-07-27 14:50 UTC, Cheremis88 commented on src/utils/api/tree.js
> +}
Так глубоко? Почему не оставить на уровне с другими апишками?

2024-07-27 14:51 UTC, Cheremis88 commented on src/store/slices/articleSlice/index.js
> +  loading: true,
Были какие-то причины для этого, но уже забыл :)

2024-07-27 14:55 UTC, Cheremis88 commented on src/components/TestTree/createTree.js
> +    return { ...item, sub_category };
Да, так будет лучше, тем более оригинал `sub_category` может пригодиться потом при поиске.

2024-07-28 19:36 UTC, Kargobober commented on src/components/ArticlesTree/TreeItem/TreeItem.css
> +  background-image: url('../../../images/tree-menu-icon.svg');
у нас в Вите настроены псевдонимы для путей. По идее в bg-image тоже должны работать \
![image](https://github.com/user-attachments/assets/00f3b284-addd-406c-90e8-ce93844eed07)

2024-07-28 19:37 UTC, Kargobober commented on src/components/ArticlesTree/TreeItem/TreeItem.css
> +  background-image: url('../../../images/tree-menu-icon.svg');
в следующие разы поправь плиз

2024-07-28 19:46 UTC, Kargobober commented on src/components/ArticlesTree/TreeItem/TreeItem.jsx
> +          className={'tree-item__arrow' + arrowExtraClass}
Неужели реакт сам вставляет пробелы между классами?

2024-07-28 19:47 UTC, Kargobober commented on src/components/ArticlesTree/TreeItem/TreeItem.jsx
> +          className={'tree-item__arrow' + arrowExtraClass}
Пробел есть, вот смотрю. И не понимаю. Как так, что за взлом матрицы?

2024-07-28 19:55 UTC, Kargobober approved these changes

2024-07-28 22:33 UTC, Cheremis88 commented on src/components/ArticlesTree/TreeItem/TreeItem.css
> +  background-image: url('../../../images/tree-menu-icon.svg');
Не будем откладывать, поправлю и в этот раз!

2024-07-28 22:35 UTC, Cheremis88 commented on src/components/ArticlesTree/TreeItem/TreeItem.jsx
> +          className={'tree-item__arrow' + arrowExtraClass}
Я просто в переменные класса вставил строку с пробелом в начале 😛

2024-07-28 22:44 UTC, merged